# Site settings
title: diego belmar
email: 
description: Una mezcla de biotecnólogo, (bio)emprendedor tecnológico y amante de las cosas geeks.<br />Traído a ustedes desde 1986 directamente desde SCL.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Diego Belmar
street_address: 
city: 
state: 
zip_code: 
country: 
phone:

icon: fa-thumbs-o-up # Font Awesome class for your site's icon

# Social settings
facebook_url: https://www.facebook.com/diego.belmar
github_url: https://github.com/diegoscl
gitlab_url: 
telegram_url: https://t.me/diegoscl
instagram_url:
linkedin_url: https://www.linkedin.com/in/diegobelmar/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/diegoscl

# Build settings
markdown: kramdown

sass:
style: compressed
