# netlify.toml
# Comandos para el deploy del sitio en la infraestructura de Netlify.
[build]
  command = "jekyll build"
  publish = "_site"
  environment = { JEKYLL_ENV="production" }

# Redirección proxy de contenido estatico alojado en B2 y cacheado por Cloudflare.
[[redirects]]
  from = "/static/*"
  to = "https://f000.backblazeb2.com/file/diegoscl/:splat"
  status = 200
  force = true
  headers = {Cache-Control = "Public, max-age=31536000", X-From = "Netlify CDN"}
  
# Redirect domain aliases to primary domain
https://belmar.cc/* https://diego.belmar.cc/:splat 301!
https://belmar.ws/* https://diego.belmar.cc/:splat 301!
https://belmar.me/* https://diego.belmar.cc/:splat 301!
https://diego.belmar.ws/* https://diego.belmar.cc/:splat 301!
https://diego.belmar.me/* https://diego.belmar.cc/:splat 301!
# https://diegoweb.netlify.com/* https://diego.belmar.cc/:splat 301!
